version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    entrypoint: >
      sh -c "chmod -R +x /docker-entrypoint-initdb.d/*.sh &&
             exec docker-entrypoint.sh postgres"
    ports:
      - "54320:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 4G

  postgres-exporter:
    image: prometheuscommunity/postgres-exporter:latest
    container_name: postgres-exporter
    restart: unless-stopped
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable"
    ports:
      - "9187:9187"
    depends_on:
      postgres:
        condition: service_healthy

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    # needed on Linux so host.docker.internal resolves:
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3030:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning:ro
      - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

  tsung-load:
    build: './tsung/config'
    volumes:
      - ./tsung/config:/tsung/config
      - ./tsung/results/load:/tsung/log
      - ./tsung/config/users.csv:/root/.tsung/users:ro
      - ./db/init.sql:/work/init.sql:ro
    ports:
      - "8091:8091"
    depends_on:
      - app
    entrypoint: >
      sh -c "until pg_isready -h postgres -U mpi; do sleep 1; done;
        PGPASSWORD=mpi psql -h postgres -U mpi -d mpi -v ON_ERROR_STOP=1 -f /work/init.sql;
        tsung -f /tsung/config/tsung-load.xml -l /tsung/log start && \
        cd /tsung/log/\$(ls -1t /tsung/log | head -n 1) && \
        /usr/local/lib/tsung/bin/tsung_stats.pl
      "
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 6G

  tsung-volume:
    build: './tsung/config'
    volumes:
      - ./tsung/config:/tsung/config
      - ./tsung/results/load:/tsung/log
      - ./tsung/config/users.csv:/root/.tsung/users:ro
    ports:
      - "8091:8091"
    depends_on:
      - app
    entrypoint: >
      sh -c "
        tsung -f /tsung/config/tsung-load.xml -l /tsung/log start && \
        cd /tsung/log/\$(ls -1t /tsung/log | head -n 1) && \
        /usr/local/lib/tsung/bin/tsung_stats.pl
      "
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 6G

  tsung-perform:
    build: './tsung/config'
    volumes:
      - ./tsung/config:/tsung/config
      - ./tsung/results/perform:/tsung/log
      - ./tsung/config/users.csv:/root/.tsung/users:ro
      - ./db/init.sql:/work/init.sql:ro
    ports:
      - "8091:8091"
    depends_on:
      - app
    entrypoint: >
      sh -c "until pg_isready -h postgres -U mpi; do sleep 1; done;
        PGPASSWORD=mpi psql -h postgres -U mpi -d mpi -v ON_ERROR_STOP=1 -f /work/init.sql;
        tsung -f /tsung/config/tsung-perform.xml -l /tsung/log start && \
        cd /tsung/log/\$(ls -1t /tsung/log | head -n 1) && \
        /usr/local/lib/tsung/bin/tsung_stats.pl
      "
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 6G

  tsung-stress-1:
    build: './tsung/config'
    volumes:
      - ./tsung/config:/tsung/config
      - ./tsung/results/stress1:/tsung/log
      - ./tsung/config/users.csv:/root/.tsung/users:ro
      - ./db/init.sql:/work/init.sql:ro
    ports:
      - "8091:8091"
    depends_on:
      - app
    entrypoint: >
      sh -c "until pg_isready -h postgres -U mpi; do sleep 1; done;
        PGPASSWORD=mpi psql -h postgres -U mpi -d mpi -v ON_ERROR_STOP=1 -f /work/init.sql;
        tsung -f /tsung/config/tsung-stress-x3.xml -l /tsung/log start && \
        cd /tsung/log/\$(ls -1t /tsung/log | head -n 1) && \
        /usr/local/lib/tsung/bin/tsung_stats.pl
      "
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 6G

  tsung-stress-2:
    build: './tsung/config'
    volumes:
      - ./tsung/config:/tsung/config
      - ./tsung/results/stress2:/tsung/log
      - ./tsung/config/users.csv:/root/.tsung/users:ro
      - ./db/init.sql:/work/init.sql:ro
    ports:
      - "8091:8091"
    depends_on:
      - app
    entrypoint: >
      sh -c "until pg_isready -h postgres -U mpi; do sleep 1; done;
        PGPASSWORD=mpi psql -h postgres -U mpi -d mpi -v ON_ERROR_STOP=1 -f /work/init.sql;
        tsung -f /tsung/config/tsung-stress-5000-reg.xml -l /tsung/log start && \
        cd /tsung/log/\$(ls -1t /tsung/log | head -n 1) && \
        /usr/local/lib/tsung/bin/tsung_stats.pl
      "
    deploy:
      resources:
        limits:
          cpus: "12.0"
          memory: 6G

  app:
    container_name: spring-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8081:8081"
      - "9010:9010"
      - "9011:9011"
    volumes:
      - ./private_key.der:/app/private_key.der:ro
      - ./public_key.der:/app/public_key.der:ro
    environment:
      DB_URL: jdbc:postgresql://postgres:5432/mpi
      DB_USERNAME: mpi
      DB_PASSWORD: mpi
      MANAGEMENT_SERVER_PORT: "8081"
      MANAGEMENT_SERVER_ADDRESS: "0.0.0.0"
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,prometheus"
      MANAGEMENT_ENDPOINT_PROMETHEUS_ENABLED: "true"
    depends_on:
      - postgres
    deploy:
      resources:
        limits:
          cpus: "2.0"
          memory: 2G

  db-init:
    image: postgres:16
    container_name: db-init
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/init.sql:/init.sql:ro
    environment:
      PGPASSWORD: mpi   # or mpi, depending which user you connect with
    command: >
      sh -c "
        echo 'Running init.sql...' &&
        psql -h postgres -U mpi -d mpi -v ON_ERROR_STOP=1 -f /init.sql
      "
    restart: "no"

  db-seed:
    image: postgres:16
    container_name: db-seed
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/seed.sql:/seed.sql:ro
    environment:
      PGPASSWORD: mpi
    entrypoint: [ "psql" ]
    command:
      - "-h"
      - "postgres"
      - "-U"
      - "mpi"
      - "-d"
      - "mpi"
      - "-v"
      - "ON_ERROR_STOP=1"
      - "-v"
      - "N_USERS=100000"
      - "-v"
      - "N_CONVOY=100000"
      - "-v"
      - "N_SUMMON=100000"
      - "-v"
      - "N_COMPLAINT=100000"
      - "-f"
      - "/seed.sql"
    restart: "no"
    stdin_open: false
    tty: false

  db-seed-x5:
    image: postgres:16
    container_name: db-seed
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/seed.sql:/seed.sql:ro
    environment:
      PGPASSWORD: mpi
    entrypoint: [ "psql" ]
    command:
      - "-h"
      - "postgres"
      - "-U"
      - "mpi"
      - "-d"
      - "mpi"
      - "-v"
      - "ON_ERROR_STOP=1"
      - "-v"
      - "N_USERS=500000"
      - "-v"
      - "N_CONVOY=500000"
      - "-v"
      - "N_SUMMON=500000"
      - "-v"
      - "N_COMPLAINT=500000"
      - "-f"
      - "/seed.sql"
    restart: "no"
    stdin_open: false
    tty: false

  schema-test:
    image: postgres:16
    container_name: schema-test
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./db/schema_test.sql:/schema_test.sql:ro
    environment:
      PGPASSWORD: mpi
    entrypoint: ["psql"]
    command:
      - "-h"
      - "postgres"
      - "-U"
      - "mpi"
      - "-d"
      - "mpi"
      - "-v"
      - "ON_ERROR_STOP=1"
      - "-f"
      - "/schema_test.sql"
    restart: "no"
    stdin_open: false
    tty: false
