server:
  port: ${SERVER_PORT:8080}
spring:
  application:
    name: MPI
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:54320/mpi}
    username: ${DB_USERNAME:mpi}
    password: ${DB_PASSWORD:mpi}
    driver-class-name: org.postgresql.Driver

private:
  key:
    filename: "private_key.der"
public:
  key:
    filename: "public_key.der"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true
  metrics:
    tags:
      application: my-spring-app
