spring:
  application:
    name: MPI
  jpa:
    generate-ddl: true
  datasource:
    url: jdbc:postgresql://localhost:54320/mpi
    username: mpi
    password: mpi
    driver-class-name: org.postgresql.Driver

private:
  key:
    filename: "private_key.der"
public:
  key:
    filename: "public_key.der"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
