create table users
(
    id       bigint generated by default as identity
        primary key,
    password varchar(255),
    username varchar(255)
);

alter table users
    owner to postgres;

create table convoy
(
    id        bigint generated by default as identity
        primary key,
    escort_id bigint not null
        constraint fkt95j7awpygu35h8i5tkj42mbl
            references users
);

alter table convoy
    owner to postgres;

create table complaint
(
    id             bigint generated by default as identity
        primary key,
    created_at     timestamp(6) not null,
    status         varchar(255) not null
        constraint complaint_status_check
            check ((status)::text = ANY
        ((ARRAY ['NEW'::character varying, 'IN_PROGRESS'::character varying, 'COMPLETED'::character varying])::text[])),
    assigned_to_id bigint
        constraint fk1cti4lm919x65nsgv4udy1nb9
            references users,
    convoy_id      bigint       not null
        constraint fklxxajtmoymkgyht52alsp31ct
            references convoy
);

alter table complaint
    owner to postgres;

create table roles
(
    user_id bigint not null
        constraint fk97mxvrajhkq19dmvboprimeg1
            references users,
    name    varchar(255)
        constraint roles_name_check
            check ((name)::text = ANY
        ((ARRAY ['RECRUIT'::character varying, 'ESCORT'::character varying, 'COMMISSAR'::character varying, 'ADMIN'::character varying, 'MILITARY_POLICE'::character varying])::text[]))
    );

alter table roles
    owner to postgres;

create table summon
(
    id              bigint generated by default as identity
        primary key,
    military_branch varchar(255),
    status          varchar(255) not null
        constraint summon_status_check
            check ((status)::text = ANY
        ((ARRAY ['NOT_STARTED'::character varying, 'IN_QUEUE'::character varying, 'SUMMONED'::character varying, 'WAITING_ESCORT'::character varying, 'IN_CONVOY'::character varying, 'DONE'::character varying])::text[])),
    convoy_id       bigint
        constraint fk9n4bq4ulywgd8a5j4gv1gavsu
            references convoy,
    user_id         bigint       not null
        constraint ukjdm32aqaprtgl7dhuyud011gk
            unique
        constraint fk3r3ot6pkgwg2o7k5662rju5a8
            references users
);

alter table summon
    owner to postgres;

